// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.iansails.img;

import com.iansails.img.Image;

privileged aspect Image_Roo_JavaBean {
    
    public String Image.getImageUrl() {
        return this.imageUrl;
    }
    
    public void Image.setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    
}
